# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  loyalty-service:
    name: loyalty-service
    container: cr.yandex/crpoaqoigck9sge4bf4s/loyalty_service
    replicaCount: 1
    env:
      DB_DSN: "host=db-service user=program password=test dbname=loyalties port=5432" # add on deploy like ""
    publishUrl: /loyalty-service-direct/
    port: 8050
    targetPort: 8050
  payment-service:
    name: payment-service
    container: cr.yandex/crpoaqoigck9sge4bf4s/payment_service
    replicaCount: 1
    env:
      DB_DSN: "host=db-service user=program password=test dbname=payments port=5432" # add on deploy
    publishUrl: /payment-service-direct/
    port: 8060
    targetPort: 8060
  reservation-service:
    name: reservation-service
    container: cr.yandex/crpoaqoigck9sge4bf4s/reservation_service
    replicaCount: 1
    env:
      DB_DSN: "host=db-service user=program password=test dbname=reservations port=5432" # add on deploy
    publishUrl: /reservation-service-direct/
    port: 8070
    targetPort: 8070
  gateway-service:
    name: gateway-service
    container: cr.yandex/crpoaqoigck9sge4bf4s/gateway_service
    replicaCount: 1
    env:
      RESERVATION_SERVICE_URL: "http://reservation-service/api/v1/"
      PAYMENT_SERVICE_URL: "http://payment-service/api/v1/"
      LOYALTY_SERVICE_URL: "http://loyalty-service/api/v1/"
    publishUrl: /
    port: 80
    targetPort: 8080